/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.AffectVar;
import org.xtext.example.mydsl.myDsl.Commande;
import org.xtext.example.mydsl.myDsl.Commandes;
import org.xtext.example.mydsl.myDsl.Expr;
import org.xtext.example.mydsl.myDsl.ExprAnd;
import org.xtext.example.mydsl.myDsl.ExprSimple;
import org.xtext.example.mydsl.myDsl.Exprs;
import org.xtext.example.mydsl.myDsl.Fonction;
import org.xtext.example.mydsl.myDsl.For;
import org.xtext.example.mydsl.myDsl.Foreach;
import org.xtext.example.mydsl.myDsl.If;
import org.xtext.example.mydsl.myDsl.Input;
import org.xtext.example.mydsl.myDsl.Output;
import org.xtext.example.mydsl.myDsl.Programme;
import org.xtext.example.mydsl.myDsl.Vars;
import org.xtext.example.mydsl.myDsl.While;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator implements IGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Programme> _filter = Iterables.<Programme>filter(_iterable, Programme.class);
    for (final Programme p : _filter) {
      CharSequence _compile = this.compile(p);
      fsa.generateFile("pp.whpp", _compile);
    }
  }
  
  private int i = 3;
  
  private int n = 1;
  
  public String indentation(final int k) {
    int j = k;
    String indent = "";
    while ((j > 0)) {
      {
        indent = (indent + " ");
        j = (j - 1);
      }
    }
    return indent;
  }
  
  public CharSequence compile(final Programme p) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<Fonction> _fonct = p.getFonct();
      for(final Fonction f : _fonct) {
        CharSequence _compile = this.compile(f);
        _builder.append(_compile, "");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
      }
    }
    return _builder;
  }
  
  public CharSequence compile(final Fonction f) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("fonction ");
    String _symbole = f.getSymbole();
    _builder.append(_symbole, "");
    _builder.append(":");
    _builder.newLineIfNotEmpty();
    _builder.append("read ");
    Input _in = f.getIn();
    CharSequence _compile = this.compile(_in);
    _builder.append(_compile, "");
    _builder.newLineIfNotEmpty();
    _builder.append("%");
    _builder.newLine();
    Commandes _com = f.getCom();
    CharSequence _compile_1 = this.compile(_com);
    _builder.append(_compile_1, "");
    _builder.newLineIfNotEmpty();
    _builder.append("%");
    _builder.newLine();
    _builder.append("write ");
    Output _out = f.getOut();
    CharSequence _compile_2 = this.compile(_out);
    _builder.append(_compile_2, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final Input i) {
    StringConcatenation _builder = new StringConcatenation();
    String _var1 = i.getVar1();
    _builder.append(_var1, "");
    {
      EList<String> _var2 = i.getVar2();
      for(final String v : _var2) {
        _builder.append(", ");
        _builder.append(v, "");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final Output o) {
    StringConcatenation _builder = new StringConcatenation();
    String _var1 = o.getVar1();
    _builder.append(_var1, "");
    {
      EList<String> _var2 = o.getVar2();
      for(final String v : _var2) {
        _builder.append(", ");
        _builder.append(v, "");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final Commandes cos) {
    StringConcatenation _builder = new StringConcatenation();
    Commande _com1 = cos.getCom1();
    CharSequence _compile = this.compile(_com1);
    _builder.append(_compile, "");
    {
      EList<Commande> _com2 = cos.getCom2();
      for(final Commande v : _com2) {
        _builder.append(", ");
        CharSequence _compile_1 = this.compile(v);
        _builder.append(_compile_1, "");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final Commande co) {
    StringConcatenation _builder = new StringConcatenation();
    {
      String _nop = co.getNop();
      boolean _notEquals = (!Objects.equal(_nop, null));
      if (_notEquals) {
        _builder.append("nop");
      }
    }
    {
      AffectVar _affectVar = co.getAffectVar();
      boolean _notEquals_1 = (!Objects.equal(_affectVar, null));
      if (_notEquals_1) {
        AffectVar _affectVar_1 = co.getAffectVar();
        CharSequence _compile = this.compile(_affectVar_1);
        _builder.append(_compile, "");
      }
    }
    {
      While _whileC = co.getWhileC();
      boolean _notEquals_2 = (!Objects.equal(_whileC, null));
      if (_notEquals_2) {
        While _whileC_1 = co.getWhileC();
        CharSequence _compile_1 = this.compile(_whileC_1);
        _builder.append(_compile_1, "");
      }
    }
    {
      For _forC = co.getForC();
      boolean _notEquals_3 = (!Objects.equal(_forC, null));
      if (_notEquals_3) {
        While _whileC_2 = co.getWhileC();
        CharSequence _compile_2 = this.compile(_whileC_2);
        _builder.append(_compile_2, "");
      }
    }
    {
      If _ifC = co.getIfC();
      boolean _notEquals_4 = (!Objects.equal(_ifC, null));
      if (_notEquals_4) {
        While _whileC_3 = co.getWhileC();
        CharSequence _compile_3 = this.compile(_whileC_3);
        _builder.append(_compile_3, "");
      }
    }
    {
      Foreach _foreachC = co.getForeachC();
      boolean _notEquals_5 = (!Objects.equal(_foreachC, null));
      if (_notEquals_5) {
        While _whileC_4 = co.getWhileC();
        CharSequence _compile_4 = this.compile(_whileC_4);
        _builder.append(_compile_4, "");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final AffectVar av) {
    StringConcatenation _builder = new StringConcatenation();
    Vars _var1 = av.getVar1();
    CharSequence _compile = this.compile(_var1);
    _builder.append(_compile, "");
    _builder.append(" := ");
    Exprs _exp = av.getExp();
    CharSequence _compile_1 = this.compile(_exp);
    _builder.append(_compile_1, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final While w) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("while");
    _builder.newLine();
    String _indentation = this.indentation(this.i);
    _builder.append(_indentation, "");
    Expr _exp2 = w.getExp2();
    CharSequence _compile = this.compile(_exp2);
    _builder.append(_compile, "");
    _builder.newLineIfNotEmpty();
    _builder.append("do ");
    _builder.newLine();
    String _indentation_1 = this.indentation(this.i);
    _builder.append(_indentation_1, "");
    Commandes _com3 = w.getCom3();
    Object _compile_1 = this.compile(_com3);
    _builder.append(_compile_1, "");
    _builder.newLineIfNotEmpty();
    _builder.append("od");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final For f) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("for");
    _builder.newLine();
    String _indentation = this.indentation(this.i);
    _builder.append(_indentation, "");
    Expr _exp3 = f.getExp3();
    CharSequence _compile = this.compile(_exp3);
    _builder.append(_compile, "");
    _builder.newLineIfNotEmpty();
    _builder.append("do");
    _builder.newLine();
    String _indentation_1 = this.indentation(this.i);
    _builder.append(_indentation_1, "");
    Commandes _com4 = f.getCom4();
    CharSequence _compile_1 = this.compile(_com4);
    _builder.append(_compile_1, "");
    _builder.newLineIfNotEmpty();
    _builder.append("od ");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final If ifc) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("if");
    _builder.newLine();
    String _indentation = this.indentation(this.i);
    _builder.append(_indentation, "");
    Expr _exp4 = ifc.getExp4();
    CharSequence _compile = this.compile(_exp4);
    _builder.append(_compile, "");
    _builder.newLineIfNotEmpty();
    _builder.append("then");
    _builder.newLine();
    String _indentation_1 = this.indentation(this.i);
    _builder.append(_indentation_1, "");
    Commandes _com5 = ifc.getCom5();
    CharSequence _compile_1 = this.compile(_com5);
    _builder.append(_compile_1, "");
    _builder.newLineIfNotEmpty();
    _builder.append("else");
    _builder.newLine();
    String _indentation_2 = this.indentation(this.i);
    _builder.append(_indentation_2, "");
    Commandes _com6 = ifc.getCom6();
    CharSequence _compile_2 = this.compile(_com6);
    _builder.append(_compile_2, "");
    _builder.newLineIfNotEmpty();
    _builder.append("fi");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final Foreach fe) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("foreach");
    _builder.newLine();
    String _indentation = this.indentation(this.i);
    _builder.append(_indentation, "");
    Expr _exp5 = fe.getExp5();
    CharSequence _compile = this.compile(_exp5);
    _builder.append(_compile, "");
    _builder.newLineIfNotEmpty();
    _builder.append("in");
    _builder.newLine();
    String _indentation_1 = this.indentation(this.i);
    _builder.append(_indentation_1, "");
    Expr _exp6 = fe.getExp6();
    CharSequence _compile_1 = this.compile(_exp6);
    _builder.append(_compile_1, "");
    _builder.newLineIfNotEmpty();
    _builder.append("do");
    _builder.newLine();
    String _indentation_2 = this.indentation(this.i);
    _builder.append(_indentation_2, "");
    Commandes _com7 = fe.getCom7();
    CharSequence _compile_2 = this.compile(_com7);
    _builder.append(_compile_2, "");
    _builder.newLineIfNotEmpty();
    _builder.append("od");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final Vars v) {
    StringConcatenation _builder = new StringConcatenation();
    return _builder;
  }
  
  public CharSequence compile(final Exprs exps) {
    StringConcatenation _builder = new StringConcatenation();
    Expr _exprS = exps.getExprS();
    CharSequence _compile = this.compile(_exprS);
    _builder.append(_compile, "");
    {
      EList<Expr> _exprS2 = exps.getExprS2();
      for(final Expr v : _exprS2) {
        _builder.append(", ");
        CharSequence _compile_1 = this.compile(v);
        _builder.append(_compile_1, "");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final Expr ex) {
    StringConcatenation _builder = new StringConcatenation();
    {
      ExprAnd _expA = ex.getExpA();
      boolean _notEquals = (!Objects.equal(_expA, null));
      if (_notEquals) {
        ExprAnd _expA_1 = ex.getExpA();
        CharSequence _compile = this.compile(_expA_1);
        _builder.append(_compile, "");
      }
    }
    {
      ExprSimple _expS = ex.getExpS();
      boolean _notEquals_1 = (!Objects.equal(_expS, null));
      if (_notEquals_1) {
        ExprSimple _expS_1 = ex.getExpS();
        CharSequence _compile_1 = this.compile(_expS_1);
        _builder.append(_compile_1, "");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence compile(final ExprSimple es) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("lol");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compile(final ExprAnd ea) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("mdr");
    _builder.newLine();
    return _builder;
  }
}
